src/main/java/am2/AMEventHandler.java
This is a fix for issue #1096 (rift storage not synchronising when in the End), and possibly for soulbound items not being saved (issue #1209 - I forget whether it was already solved when I started banging away at the newly-released source...). Because Mojang are weird, they hardcoded End portals to always send you to dimension 1 regardless of where you are, and then put in a special case test to see if you're going from 1 to 1.
This special case test doesn't fire a dimension transfer event, so the extended properties (rift storage, magic levels, etc.) never get saved and you lose everything when the game creates you anew.
What does trigger, however, is an achievement - which does have an event of its own. I hook that and use it to save the extended properties data (but not the soulbound …
=> Fix rift storage and soulbound items in the End

src/main/java/am2/items/ItemEssenceBag.java
Issue #1178 (arcane essences are erased by the essence bag) was marked as fixed during dev, but I'm assuming that it's one of the things that was lost since the issue appears to be present in the released source. I've fixed it here by removing the metadata == 0 check and forcing it to always save the metadata - this appears to have solved the problem.
There was also a part of the code at the beginning of the file which required the user to be sneaking in order to open the bag. I don't like this behaviour - it's inconsistent with all other personal inventory items, so I removed it. This is not related to the bugfix and is a preference of mine.
=> Re-fix issue #1178, remove sneaking requirement to open essence bag

src/main/java/am2/blocks/BlockKeystoneDoor.java
Issue #1085 (keystone doors drop wooden doors) was marked as fixed during dev, but I'm assuming that this was some of the work which was lost. I've re-fixed that by adding the same override code which vanilla wooden doors have, altered to drop keystone door items.
=> Re-fix issue #1085

src/main/java/am2/blocks/tileentities/TileEntityArcaneDeconstructor.java
This fixes issue #1199 (dupe bug with the arcane deconstructor) by implementing exactly what @raymondhardy suggested in his bug report - an additional check for the item's recipe just before completion. Items without a recipe (such as his example of sticks) get destroyed.
One additional change is that container items are no longer returned - this was from testing out fixes for issue #1029 (magician's workbench bucket duplication), cutting off a potential duplication bug in the process (to test, put cake in the arcane deconstructor). This means that you will lose the milk, water, resonant ender or any other such fluids used to craft an item, but I'm not particularly bothered about a less than 100% return on something you were never able to do in the first place.
=> Fix for issue #1199

src/main/java/am2/containers/slots/SlotMagiciansWorkbenchCrafting.java
This is a fix for issue #1029 (bucket duplication in the magician's workbench), which was readily reproducible when making cake on the first source release. My fix was to remove the check about whether container items should stay in the inventory and to just replace them where they sit - duplicate buckets are therefore not stuffed into the player's inventory and mass is conserved.
A perfect fix would move the excess container items to the workbench's inventory, the players inventory or the space under the player's nose if both are full, and I can see a way to implement that, but I'll have to come back to that when I get more time after looking at the rest of the bugs.
=> Fixes issue #1029

src/main/java/am2/items/ItemCandle.java, src/main/resources/assets/arsmagica2/lang/en_US.lang
I was able to very reliably reproduce issue #1131 in the initial source release (get warding candle, right-click on iron/gold ores, works fine; right-click on redstone ore and it breaks horribly). My issue here was that the final null pointer was in Mojang's code:
```
java.lang.NullPointerException
at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:427) ~[ItemStack.class:?]
at am2.items.ItemCandle.getItemStackDisplayName(ItemCandle.java:174) ~[ItemCandle.class:?]
```
Because of this, adding an effective null check (I tried it, it didn't work) would involve either duplicating whatever it is that ItemStack is doing, but with more null checks, or by completely changing the warding candle code to use block names (eg: minecraft:lit_redstone_ore) and then trying to get a localised …
=> Fix for issue #1131 (warding candle crash on redstone ore)

src/main/java/am2/buffs/BuffList.java, src/main/java/am2/configuration/AMConfig.java, src/main/java/am2/proxy/CommonProxy.java
While testing AM2 in my full modpack, I noticed that the mana potions seemed to have a hard-coded ID and could not be changed through the config file. This caused the game to not start when DragonAPI detected a potion clash with a debuff from RotaryCraft, threw an error to tell me what was going on and (rightfully) halted execution.
The cause was mana potions not being created the same way as other buffs - instead of using the createAMPotion() function which searches the config file for a potion ID, it just created a new potion directly using a hardcoded index. I've added a function to BuffList.java for mana potions which replicates the functionality of createAMPotion(), which means that the mana potions now have config file entries.
This is the main purpose of the pull request.
The …
=> Automatic allocation (kinda) for potion IDs, allows configuration of mana potion ID

src/main/java/am2/entities/EntitySpellProjectile.java
In the process of working with `EntityDragonPart` (should be named `EntityPart`, as it isn't specific to the ender dragon), I inadvertently found the source of the bug where projectile spells would have no effect on the ender dragon.
A projectile spells check if it hits an entity that extends `EntityLivingBase` so that it can do damage and apply status effects. However, entity parts only extend `Entity`, causing the spell to ignore all `EntityDragonPart` entities.
To fix this, I use the exact same method `EntityPlayer.attackTargetEntityWithCurrentItem()` uses to attack an entity part: check if the struck entity is a part, then set the struck entity to the parent of the part.
=> Fixed spell projectiles targeting entity parts

src/main/java/am2/PlayerTracker.java
Fixes #1122, where in rare cases an in-game username change would cause what appears to be a wipe of all spell progress and extra player properties.
=> Store player data in memory via UUID instead of by username

src/main/java/am2/bosses/AM2Boss.java
Whoops, looks like there's a small quirk with the minecraft engine where a projectile can't hit an entity part (`EntityDragonPart`) without first hitting the parent entity, so my extra large body parts of the bosses were not being taken into account by projectiles (melee attacks work just fine, projectiles sometimes appear to work but actually don't).
My alternate method is to give the entity parts a little more form by directly spawning them into the world, not just counting on MC's code to manage them. After a few tweaks and many many tests later, this is what the end result is.
Again, the only bug that might pop up is if a player tries to right-click/interact with a boss, the action may be cancelled (touch spells still work).
=> Fixed boss bounding boxes not properly responding to projectiles

src/main/java/am2/blocks/renderers/TechneBlockRenderHandler.java
After digging through to try and fix #1243, I eventually found that tile entities were being rendered twice, once as the block and once as the tile entity.
This worked just fine until a tile entity called a different renderer (e.g. the calcinator calling the item renderer to display the smelting item) and the block was being broken at the same time. The tile entity render would occur just fine, but the block render would cause the client to crash as the client tried to tessellate both the non-tile renderer and the block renderer at the same time.
This pull request fixes #1243 and similar issues by removing the extra block render.
=> Fix tile entities double-rendering and sometimes crashing clients when broken

src/main/java/am2/spell/components/Grow.java
The Grow Component behaves weird and I tried to clean it up a bit.
This commit applies the vanilla bonemeal effect to *all* IGrowables every now and then (``world.rand.nextInt(10) < 8``) if they are not specifically handled before. Before, nothing happened when applied to grass. I don't know why this doesn't work even though this has been fixed in #594.
This works just fine with projectile but there is still a bug with "Zone+AoE". You need to dig one block below the surface where you want to apply the effect. I think this is a bug in Zone+AoE which does not search the blocks properly.
=> Grow component: Apply bonemeal-like effect to all growables

src/main/resources/assets/arsmagica2/lang/de_DE.lang, src/main/resources/assets/arsmagica2/lang/en_US.lang
This adds the name for the tile "Liquid Etherium" and a name for the fluid "Liquid Etherium".
This way it can be properly shown in Waila, NEI and in liquid storage tanks from mods like Railcraft or Thermal Expansion.
=> add liquid etherium name for containers and NEI/waila

src/main/java/am2/blocks/tileentities/TileEntityObelisk.java
Pretty straightforward fix: only have the server send the update to clients, not the client.
=> Fixed #1221 of an occasional NPE thrown by an updating Obelisk

src/main/java/am2/damage/DamageSourceDarkNexus.java, src/main/java/am2/damage/DamageSourceFire.java, src/main/java/am2/damage/DamageSourceFrost.java, src/main/java/am2/damage/DamageSourceHoly.java, src/main/java/am2/damage/DamageSourceLightning.java, src/main/java/am2/damage/DamageSourceUnsummon.java, src/main/java/am2/damage/DamageSourceWTFBoom.java, src/main/java/am2/damage/DamageSourceWind.java, src/main/resources/assets/arsmagica2/lang/en_US.lang
Modified some of the death messages to better match Minecraft's "death by X because of X" messages.
This also fixes #1194 and similar unlocalized death messages. Some mobs from mods are specially named, so their death is announced. Originally, localization only happened if the dying entity was a player, so I tweaked the death messages to support all entities.
I was a little creative with the holy death message and the dark nexus death message, so feel free to adjust as you feel necessary.
=> Death message tweaks

src/main/java/am2/AMCore.java, src/main/java/am2/commands/ConfigureAMUICommand.java, src/main/java/am2/network/AMPacketIDs.java, src/main/java/am2/network/AMPacketProcessorClient.java, src/main/java/am2/proxy/gui/ServerGuiManager.java, src/main/java/am2/proxy/tick/ClientTickHandler.java
Fixes #1114, where the client would ask the server to open the AMUICFG gui.
I had to stick the method call to open the GUI in an anonymous thread because the newly opened GUI opened so fast that the command to close the chat GUI would also close the UI config.
If there's a better way to get the right GUI to open and stay open, feel free to implement that.
(Also made sure to test the standalone server this time, and it does work)
=> Fix AMUICFG command asking for permission from server

src/main/java/am2/AMEventHandler.java
Turns out there's a priority modifier for events, so let's have AM2 have a high priority since it has ways of mitigating death and mods that count deaths or trigger something after a death usually are a lower priority.
This should fix #1116, but it is possible the CME could pop up again due to another mod.
=> Set AM2 EntityDeathEvent to highest priority

src/main/java/am2/spell/components/Dispel.java
This a fix for part of #1220, caused by the server and client timings being just off enough that Dispel thinks there is a shield effect to dispel, when in reality there is not, as the server ran the shield effect after dispel.
=> Fix dispel desyncing from server

src/main/java/am2/AMChunkLoader.java, src/main/java/am2/api/power/PowerTypes.java, src/main/java/am2/armor/infusions/ImbuementRegistry.java, src/main/java/am2/blocks/tileentities/TileEntityInscriptionTable.java, src/main/java/am2/blocks/tileentities/flickers/FlickerOperatorRegistry.java, src/main/java/am2/buffs/BuffList.java, src/main/java/am2/configuration/AMConfig.java, src/main/java/am2/enchantments/AMEnchantments.java, src/main/java/am2/entities/EntityManager.java, src/main/java/am2/entities/SpawnBlacklists.java, src/main/java/am2/entities/ai/EntityAIApplyPotionOnCollide.java, src/main/java/am2/items/ItemsCommonProxy.java, src/main/java/am2/lore/ArcaneCompendium.java, src/main/java/am2/lore/CompendiumEntrySpellComponent.java, src/main/java/am2/lore/CompendiumEntrySpellModifier.java, src/main/java/am2/lore/CompendiumEntrySpellShape.java, src/main/java/am2/network/AMPacketProcessorClient.java, src/main/java/am2/playerextensions/SkillData.java, src/main/java/am2/power/PowerNodeCache.java, src/main/java/am2/power/PowerNodeEntry.java, src/main/java/am2/power/PowerNodeRegistry.java, src/main/java/am2/preloader/BytecodeTransformers.java, src/main/java/am2/proxy/tick/ClientTickHandler.java, src/main/java/am2/spell/SkillManager.java, src/main/java/am2/spell/SkillTreeManager.java, src/main/java/am2/spell/SpellRecipeManager.java, src/main/java/am2/spell/SpellTextureHelper.java, src/main/java/am2/worldgen/RetroactiveWorldgenerator.java
Whoops, accidentally removed formatted strings from logs.
This is a little messy, and if wanted we can make a `LogHelper`class similar to `FMLLog` so we don't have to worry about manually running a string through String.format().
=> Fixed a log format mistake

src/main/java/am2/spell/components/Reflect.java
When trying to put Reflect in a spell, one of its required components is "logWood", which is not a valid item (the crafting altar doesn't seem to like ore dictionary lookups). I've changed it to explicitly require a witchwood log, which both fixes the issue and seems more thematically appropriate to the spell than a lump of dead mundane tree.
=> Fix for non-craftable reflect spell component

src/main/java/am2/blocks/BlocksCommonProxy.java, src/main/java/am2/items/ItemsCommonProxy.java, src/main/resources/assets/forge/lang/en_US.lang, src/main/resources/assets/forge/lang/es_ES.lang, src/main/resources/assets/forge/lang/fr_FR.lang, src/main/resources/pack.mcmeta
Changelog:
- Converted all (hopefully) recipes to use Ore Dictionary
- Registered chests and crafting tables in Ore Dictionary to support ganymedes01's [WoodStuff mod](https://github.com/ganymedes01/WoodStuff)
- Removed Forge assets. These are not needed to be in the mod.
- Added pack.mcmeta (Simple file which removes annoying FML log message "missing pack.mcmeta")
=> Ore Dictionary support for recipes

src/main/java/am2/blocks/PoweredBlock.java, src/main/java/am2/blocks/tileentities/TileEntityAMPower.java, src/main/java/am2/blocks/tileentities/TileEntityKeystoneRecepticle.java
From discussion in #1280, this should remove a power node no matter what way a block or tile entity is removed.
Is there a reason onDeath() is separate from invalidate()? It would be a whole lot easier to just have onDeath() called by invalidate().
=> Tweaked power blocks to update power node registry no mater what method of removal

src/main/resources/assets/arsmagica2/lang/de_DE.lang, src/main/resources/assets/arsmagica2/lang/en_US.lang, src/main/resources/assets/arsmagica2/lang/es_ES.lang, src/main/resources/assets/arsmagica2/lang/nl_NL.lang, src/main/resources/assets/arsmagica2/lang/ru_RU.lang, src/main/resources/assets/arsmagica2/lang/zh_CN.lang
When you spawn a Rift entity (via a Rift spell) it had no name. I just copied the name of the spell to the entity for all languages.
=> Fixing Rift entity name

src/main/java/am2/spell/components/Grow.java
I rewrote the whole Grow component to allow growing of non-vanilla flowers and plants. Additionally I nerfed the spell a lot, such that you need more than one attempt to grow a flower.
I also removed the particle effect on a hit if the target can't grow anything. This way you know if you should hit it more often to grow something or if you should move on.
I will remove the farmland commit once the discussion in #1291 has come to the conclusion.
=> Rewrite grow spell component

src/main/java/am2/AMClientEventHandler.java, src/main/java/am2/AMEventHandler.java
Fixed #1289 by removing the chrono anchor effect when an entity is spawned into a world (e.g. after it changes dimensions).
=> Fixed chrono anchor dimension bug

src/main/java/am2/AMKeyBindings.java
=> Fix crash caused by cycling spell shape with an empty spell book

src/main/java/am2/worldgen/BiomeWitchwoodForest.java, src/main/java/am2/worldgen/WitchwoodTreeHuge.java, src/main/java/am2/worldgen/WitchwoodTreeSmall.java
This is a fix for issue #1284, caused by the wrong function being over-ridden in BiomeWitchwoodForest.java. func_150567_a(), which returns a WorldGenAbstractTree, is what gets called by the biome decorator, and wasn't over-ridden. This caused Minecraft to revert to its default tree generation behaviour - oak trees.
I've fixed this, and also copied the generation code from the vanilla class (WorldGenTrees.java) into WitchwoodTreeSmall (which didn't have any tree generation code), removed some un-necessary bits (vine and cocoa pod generation) and given the variables more meaningful names than "byte b0" and "int i1".
Witchwood forests now generate witchwood trees as expected. Almost all of them are "small" trees, the same shape as trees that you'll find in vanilla MC forest biomes.
=> Fix for issue #1284 (witchwood forests do not spawn witchwood trees

src/main/java/am2/blocks/AMFlower.java, src/main/java/am2/blocks/BlockTarmaRoot.java, src/main/java/am2/spell/components/Grow.java, src/main/java/am2/worldgen/AM2FlowerGen.java
Currently, Tarma root can grow (naturally and via the growth spell component) on all stone and cobblestone blocks, no matter if it's dark or not.  This change fixes the behaviour and adjusts it such that it only grows in places with ``lightlevel < 4`` and respects the "EnumPlantType.Cave``, similar to the behaviour of mushrooms.
=> Fix Tarma Root growth

src/main/java/am2/entities/EntityBroom.java, src/main/java/am2/entities/ai/EntityAIChestDeposit.java
This is a plain renaming of ``getInventory``. ``getInventory()`` would override an implementation in ``EntityLiving`` with the stable10 or later mappings. 
In order to avoid this in the future and to clearly state that the ``getInventory()`` is only valid for Broom,  this PR renames the method.
This commit is based on 967f9fa43735f745007db39c26bacdfd94040637.
=> Broom: rename getInventory -> getBroomInventory

src/main/java/am2/proxy/tick/ClientTickHandler.java, src/main/java/am2/proxy/tick/ServerTickHandler.java, src/main/java/am2/spell/components/EnderIntervention.java, src/main/java/am2/utility/DimensionUtilities.java
Hello again!
Sorry for the (considerably long) delay for this fix, life got busy for me.
Anyway, I've done some testing with this fix (repeatedly going "up and down" between the nether and the overworld), and I believe this solves #1146.
I also noticed there seems to be some differences between what events fire on what ticks between client (singleplayer) worlds and server worlds. While that's not in the scope of this pull request, it may be something to consider cleaning or clarifying later on.
Fingers crossed this squashes that bug for good!
=> Modified dimension transfers, should fix #1146

src/main/java/am2/AMClientEventHandler.java, src/main/java/am2/proxy/ClientProxy.java, src/main/java/am2/proxy/CommonProxy.java
I found a bug that would sometimes cause MC to "break" away from the spell book while the player was scrolling in the scroll book. I figured out that outright cancelling the mouse event when it's triggered works very well in fixing this bug, and I modified the scroll handling code to do so.
=> Fixed some scroll bugs

src/main/java/am2/utility/DummyEntityPlayer.java
I was testing bosses and noticed that the Fire Guardian's firestorm spell, if it killed a player, caused the message "jjtParadox went up in flames because of dummyplayer".
I found that the firestorm spell created a dummy player that did the damage to entities, and said dummy player had the name "dummyplayer". This changes the dummy player so that if it is created from a parent entity, the dummy player takes on the name of the entity that created it.
=> Fixed dummy player name showing up in some death messages

src/main/resources/assets/arsmagica2/docs/ArcaneCompendium_en_US.xml
The Telekinesis entry in the Compendium was mislabeled as requiring sneak to be held to change the telekinesis distance. That was causing some confusion and frustration over using Telekinesis with a spell book, but that should be fixed now.
=> Corrected Telekinesis entry

src/main/java/am2/blocks/BlockAMOre.java, src/main/java/am2/blocks/WitchwoodPlanks.java, src/main/java/am2/blocks/WitchwoodSlabs.java, src/main/java/am2/blocks/WitchwoodStairs.java
There was an old problem with a hardcoded harvestlevel for ores, and I found that witchwood slabs were also not matching the harvestlevel or witchwood planks and stairs, which this fixes.
(I will also try to port this to @williewillus's 1.8 branch)
=> Fixed harvestlevel for ores and witchwood

src/main/java/am2/ItemFrameWatcher.java
One of the issues reported was somehow caused by a null sneaking in where I thought it shouldn't be able to sneak into. No clue how often that'll happen, but this null check should fix the edge case where it does happen.
=> Added null check to frame watcher

src/main/java/am2/RitualShapeHelper.java, src/main/java/am2/entities/EntityItemRune.java, src/main/java/am2/items/ItemRune.java
I slightly modified rituals to handle stacked items as individual items.
I also modified runes so that they do not combine if dropped next to each other. This is because the order runes are dropped matters for the rituals to work correctly, and runes that combine into a larger stack can break the order of the dropped runes.
This is verified to not break spell crafting with runes.
=> Fix for stacked items causing rituals to break (Addresses part of #1399)

src/main/java/am2/armor/AMArmor.java
Just added void damage to the excluded damage list.
EDIT: I meant "fixes #1314"
=> Fix for void damage damaging AM armor, fixes #1314

src/main/java/am2/spell/components/Absorption.java
Adds an absorption spell component that will add some absorption hearts to the player. Player cannot have more than the base absorption hearts given by the spell (buffed by the buff power modifier).
Component is not accessible in-game yet, as it hasn't been added to the component lists or the spell trees.
=> Absorption

src/main/java/am2/AMEventHandler.java, src/main/java/am2/buffs/BuffEffectSwiftSwim.java
performEffect() is only called server side (worldObj.isRemote == false), however the server doesn't know the players speed, so multiplying it doesn't work. The event listener runs on both sides, so putting the code there makes it work.
=> Fixed Swift Swim not doing anything

src/main/java/am2/spell/SpellTextureHelper.java
This fixes 2 problems with spell texture loading.
1. Strings should always be compared with .equals(). == checks if they are the same instance. The only reason this worked is because both strings are string constants
2. Sort the ArrayList. The current code assumes that jarFile.entries() always lists entries in alphabetical order, which is not true. It's implementation specific.
=> Fixed problems with spell texture loading

src/main/java/am2/AMEventHandler.java
This fixes the leap level being one off.  
Without this Leap I has the effect of Leap II, Leap II the effect of Leap III and Leap III does nothing at all. (See #1174, #1397, #1612)
=> Fixed Leap levels shifted by one

src/main/resources/assets/arsmagica2/docs/ArcaneCompendium_zh_CN.xml
There are invalid XML structures in the `docs/ArcaneCompendium_zh_CN.xml` file, which lead to an empty Arcane Compendium book for Chinese players.
These commits fix the XML file structure, and set the encoding to `UTF-8`.
I have tested the fixed version with `Forge10.13.4.1558-1.7.10`, it works well.
=> Fix zh_CN translation docs file

src/main/java/am2/blocks/BlocksCommonProxy.java
This will allow mods to call for witchwood specifically for integration if needed
Also, added definitions for leaves.
=> Added specific oredictionaries for witchwood
